### ISSUE TITLE
where is 'kvplm_pretrained/ckpt_KV_1.pt' and 'gin_pretrained/graphMVP.pth' ？

### ISSUE THREAD

**Issue by Haoxu11225** [yangzhao1230/GraphTextRetrieval#4]
I read your README file in detail, but running your code is a difficult thing, you load the two pre-trained models separately, but can't find those pre-trained models。Can you give me some help in order to reproduce your article？Thanks！

**Comment by Haoxu11225** [comment]
Also can you update the README file, it seems to be a very old version.Thanks!

**Comment by yangzhao1230** [comment]
Maybe you could refer to https://github.com/ddz16/MoMu for how to load and use pre-trained models. I apologize for not having updated this repository for a long time. As I am no longer involved in this project, I may not have the bandwith to organize it in detail anymore. I'm very sorry for any inconvenience.
